/* tslint:disable */
/* eslint-disable */
/**
 * Kawara API definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetGoogleOauth2UathorizeURLResponse
 */
export interface GetGoogleOauth2UathorizeURLResponse {
    /**
     * 
     * @type {string}
     * @memberof GetGoogleOauth2UathorizeURLResponse
     */
    authorizeUrl: string;
}

export function GetGoogleOauth2UathorizeURLResponseFromJSON(json: any): GetGoogleOauth2UathorizeURLResponse {
    return GetGoogleOauth2UathorizeURLResponseFromJSONTyped(json, false);
}

export function GetGoogleOauth2UathorizeURLResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetGoogleOauth2UathorizeURLResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'authorizeUrl': json['authorize_url'],
    };
}

export function GetGoogleOauth2UathorizeURLResponseToJSON(value?: GetGoogleOauth2UathorizeURLResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'authorize_url': value.authorizeUrl,
    };
}

