# frozen_string_literal: true

source "https://rubygems.org"

gem "sinatra"
gem "sinatra-contrib"

gem "committee"
gem "oauth2"
gem "puma"
gem "rake"
gem "sorbet-runtime"

gem "redis-rack"
gem "rack-cors"

group :development do
  gem "sorbet"
  gem "tapioca", require: false

  gem "rubocop", require: false
  gem "rubocop-rake", require: false
end

group :test do
  gem "rack-test"
  gem "test-unit"
end

group :development, :test do
  gem "dotenv"
end
