# frozen_string_literal: true

require "rake/testtask"
require "rubocop/rake_task"

Rake::TestTask.new do |t|
  t.libs << "test"
  t.test_files = FileList["test/**/test*.rb"]
  t.verbose = true
end

RuboCop::RakeTask.new

desc "Run bundle exec srb tc"
task :srb do
  `bundle exec srb tc`
end

task default: %i[rubocop srb test]
