/* tslint:disable */
/* eslint-disable */
/**
 * Kawara API definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    GetGoogleOauth2UathorizeURLResponse,
    GetGoogleOauth2UathorizeURLResponseFromJSON,
    GetGoogleOauth2UathorizeURLResponseToJSON,
} from '../models';

/**
 * 
 */
export class GoogleOauth2Api extends runtime.BaseAPI {

    /**
     */
    async getGoogleOauth2UathorizeURLRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<GetGoogleOauth2UathorizeURLResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/auth/google/authorize_url`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetGoogleOauth2UathorizeURLResponseFromJSON(jsonValue));
    }

    /**
     */
    async getGoogleOauth2UathorizeURL(initOverrides?: RequestInit): Promise<GetGoogleOauth2UathorizeURLResponse> {
        const response = await this.getGoogleOauth2UathorizeURLRaw(initOverrides);
        return await response.value();
    }

}
