# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `openapi_parser` gem.
# Please instead update this file by running `bin/tapioca gem openapi_parser`.

module OpenAPIParser
  class << self
    # Load schema in specified filepath. If file path is relative, it is resolved using working directory.
    #
    # @return [OpenAPIParser::Schemas::OpenAPI]
    def load(filepath, config = T.unsafe(nil)); end

    # Load schema located by the passed uri. Uri must be absolute.
    #
    # @return [OpenAPIParser::Schemas::OpenAPI]
    def load_uri(uri, config:, schema_registry:); end

    # Load schema hash object. Uri is not set for returned schema.
    #
    # @return [OpenAPIParser::Schemas::OpenAPI]
    def parse(schema, config = T.unsafe(nil)); end

    # @param filepath [String] Path of the file containing the passed schema.
    #   Used for resolving remote $ref if provided.
    #   If file path is relative, it is resolved using working directory.
    # @return [OpenAPIParser::Schemas::OpenAPI]
    def parse_with_filepath(schema, filepath, config = T.unsafe(nil)); end

    private

    def file_uri(filepath); end
    def load_hash(hash, config:, uri:, schema_registry:); end
    def parse_file(content, extension); end
    def parse_json(content); end
    def parse_yaml(content); end
  end
end

class OpenAPIParser::Config
  # @return [Config] a new instance of Config
  def initialize(config); end

  def coerce_value; end
  def datetime_coerce_class; end
  def expand_reference; end

  # @return [OpenAPIParser::SchemaValidator::Options]
  def path_params_options; end

  # @return [OpenAPIParser::SchemaValidator::Options]
  def request_body_options; end

  # @return [OpenAPIParser::SchemaValidator::Options]
  def request_validator_options; end

  # @return [OpenAPIParser::SchemaValidator::ResponseValidateOptions]
  def response_validate_options; end

  def strict_response_validation; end
  def validate_header; end
end

module OpenAPIParser::Expandable
  # expand refs
  #
  # @param root [OpenAPIParser::Schemas::Base]
  # @return nil
  def expand_reference(root); end

  private

  def expand_hash_attribute(root, name); end
  def expand_hash_objects(root, attribute_names); end
  def expand_list_objects(root, attribute_names); end
  def expand_object(root, object); end
  def expand_objects(root, attribute_names); end

  # @param root [OpenAPIParser::Schemas::OpenAPI]
  # @param reference [OpenAPIParser::Schemas::Reference]
  def referenced_object(root, reference); end
end

module OpenAPIParser::Findable
  # @param reference [String]
  # @return [OpenAPIParser::Findable]
  def find_object(reference); end

  def purge_object_cache; end

  private

  def find_remote_object(reference); end
end

class OpenAPIParser::InvalidDateFormat < ::OpenAPIParser::OpenAPIError
  # @return [InvalidDateFormat] a new instance of InvalidDateFormat
  def initialize(value, reference); end

  def message; end
end

class OpenAPIParser::InvalidEmailFormat < ::OpenAPIParser::OpenAPIError
  # @return [InvalidEmailFormat] a new instance of InvalidEmailFormat
  def initialize(value, reference); end

  def message; end
end

class OpenAPIParser::InvalidPattern < ::OpenAPIParser::OpenAPIError
  # @return [InvalidPattern] a new instance of InvalidPattern
  def initialize(value, pattern, reference, example); end

  def message; end
end

class OpenAPIParser::InvalidUUIDFormat < ::OpenAPIParser::OpenAPIError
  # @return [InvalidUUIDFormat] a new instance of InvalidUUIDFormat
  def initialize(value, reference); end

  def message; end
end

class OpenAPIParser::LessThanExclusiveMinimum < ::OpenAPIParser::OpenAPIError
  # @return [LessThanExclusiveMinimum] a new instance of LessThanExclusiveMinimum
  def initialize(value, reference); end

  def message; end
end

class OpenAPIParser::LessThanMinItems < ::OpenAPIParser::OpenAPIError
  # @return [LessThanMinItems] a new instance of LessThanMinItems
  def initialize(value, reference); end

  def message; end
end

class OpenAPIParser::LessThanMinLength < ::OpenAPIParser::OpenAPIError
  # @return [LessThanMinLength] a new instance of LessThanMinLength
  def initialize(value, reference); end

  def message; end
end

class OpenAPIParser::LessThanMinimum < ::OpenAPIParser::OpenAPIError
  # @return [LessThanMinimum] a new instance of LessThanMinimum
  def initialize(value, reference); end

  def message; end
end

module OpenAPIParser::MediaTypeSelectable
  private

  # select media type by content_type (consider wild card definition)
  #
  # @param content_type [String]
  # @param content [Hash{String => OpenAPIParser::Schemas::MediaType}]
  # @return [OpenAPIParser::Schemas::MediaType, nil]
  def select_media_type_from_content(content_type, content); end
end

class OpenAPIParser::MoreThanExclusiveMaximum < ::OpenAPIParser::OpenAPIError
  # @return [MoreThanExclusiveMaximum] a new instance of MoreThanExclusiveMaximum
  def initialize(value, reference); end

  def message; end
end

class OpenAPIParser::MoreThanMaxItems < ::OpenAPIParser::OpenAPIError
  # @return [MoreThanMaxItems] a new instance of MoreThanMaxItems
  def initialize(value, reference); end

  def message; end
end

class OpenAPIParser::MoreThanMaxLength < ::OpenAPIParser::OpenAPIError
  # @return [MoreThanMaxLength] a new instance of MoreThanMaxLength
  def initialize(value, reference); end

  def message; end
end

class OpenAPIParser::MoreThanMaximum < ::OpenAPIParser::OpenAPIError
  # @return [MoreThanMaximum] a new instance of MoreThanMaximum
  def initialize(value, reference); end

  def message; end
end

class OpenAPIParser::NotAnyOf < ::OpenAPIParser::OpenAPIError
  # @return [NotAnyOf] a new instance of NotAnyOf
  def initialize(value, reference); end

  def message; end
end

class OpenAPIParser::NotEnumInclude < ::OpenAPIParser::OpenAPIError
  # @return [NotEnumInclude] a new instance of NotEnumInclude
  def initialize(value, reference); end

  def message; end
end

class OpenAPIParser::NotExistContentTypeDefinition < ::OpenAPIParser::OpenAPIError
  def message; end
end

class OpenAPIParser::NotExistDiscriminatorMappedSchema < ::OpenAPIParser::OpenAPIError
  # @return [NotExistDiscriminatorMappedSchema] a new instance of NotExistDiscriminatorMappedSchema
  def initialize(mapped_schema_reference, reference); end

  def message; end
end

class OpenAPIParser::NotExistDiscriminatorPropertyName < ::OpenAPIParser::OpenAPIError
  # @return [NotExistDiscriminatorPropertyName] a new instance of NotExistDiscriminatorPropertyName
  def initialize(key, value, reference); end

  def message; end
end

class OpenAPIParser::NotExistPropertyDefinition < ::OpenAPIParser::OpenAPIError
  # @return [NotExistPropertyDefinition] a new instance of NotExistPropertyDefinition
  def initialize(keys, reference); end

  def message; end
end

class OpenAPIParser::NotExistRequiredKey < ::OpenAPIParser::OpenAPIError
  # @return [NotExistRequiredKey] a new instance of NotExistRequiredKey
  def initialize(keys, reference); end

  def message; end
end

class OpenAPIParser::NotExistStatusCodeDefinition < ::OpenAPIParser::OpenAPIError
  def message; end
end

class OpenAPIParser::NotNullError < ::OpenAPIParser::OpenAPIError
  def message; end
end

class OpenAPIParser::NotOneOf < ::OpenAPIParser::OpenAPIError
  # @return [NotOneOf] a new instance of NotOneOf
  def initialize(value, reference); end

  def message; end
end

class OpenAPIParser::OpenAPIError < ::StandardError
  # @return [OpenAPIError] a new instance of OpenAPIError
  def initialize(reference); end
end

module OpenAPIParser::ParameterValidatable
  # @param path_item [PathItem] parent
  def set_parent_path_item(path_item); end

  # @param path_params [Hash] path parameters
  # @param options [OpenAPIParser::SchemaValidator::Options] request validator options
  def validate_path_params(path_params, options); end

  # @param params [Hash] parameter hash
  # @param headers [Hash] headers hash
  # @param options [OpenAPIParser::SchemaValidator::Options] request validator options
  def validate_request_parameter(params, headers, options); end

  private

  # @return [Hash{String => Hash{String => Parameter}}] hash[in][name] => Parameter
  def divided_parameter_hash; end

  def header_parameter_hash; end
  def path_parameter_hash; end
  def query_parameter_hash; end

  # @param headers [Hash] header hash
  # @param object_reference [String]
  # @param options [OpenAPIParser::SchemaValidator::Options] request validator options
  def validate_header_parameter(headers, object_reference, options); end

  # @param params [Hash] query parameter hash
  # @param object_reference [String]
  # @param options [OpenAPIParser::SchemaValidator::Options] request validator options
  def validate_query_parameter(params, object_reference, options); end
end

class OpenAPIParser::ParameterValidator
  class << self
    # @param parameters_hash [Hash{String => Parameter}]
    # @param params [Hash]
    # @param object_reference [String]
    # @param options [OpenAPIParser::SchemaValidator::Options]
    # @param is_header [Boolean] is header or not (ignore params key case)
    # @raise [OpenAPIParser::NotExistRequiredKey]
    def validate_parameter(parameters_hash, params, object_reference, options, is_header = T.unsafe(nil)); end

    private

    def convert_key(k, is_header); end
  end
end

module OpenAPIParser::Parser
  mixes_in_class_methods ::OpenAPIParser::Parser::ClassMethods

  # @return [Hash{String => OpenAPIParser::Schemas::Base}]
  def _openapi_all_child_objects; end

  # @param old [OpenAPIParser::Schemas::Base]
  # @param new [OpenAPIParser::Schemas::Base]
  def _update_child_object(old, new); end

  # load data by schema definition in core and set children to _openapi_all_child_objects
  #
  # @return nil
  def load_data; end

  class << self
    # @private
    def included(base); end
  end
end

module OpenAPIParser::Parser::ClassMethods
  extend ::Forwardable

  def _openapi_attr_hash_body_objects(*args, **_arg1, &block); end
  def _openapi_attr_hash_objects(*args, **_arg1, &block); end
  def _openapi_attr_list_objects(*args, **_arg1, &block); end
  def _openapi_attr_objects(*args, **_arg1, &block); end
  def _openapi_attr_values(*args, **_arg1, &block); end
  def _parser_core; end
  def openapi_attr_hash_body_objects(*args, **_arg1, &block); end
  def openapi_attr_hash_object(*args, **_arg1, &block); end
  def openapi_attr_list_object(*args, **_arg1, &block); end
  def openapi_attr_object(*args, **_arg1, &block); end
  def openapi_attr_objects(*args, **_arg1, &block); end
  def openapi_attr_value(*args, **_arg1, &block); end
  def openapi_attr_values(*args, **_arg1, &block); end
end

class OpenAPIParser::Parser::Core
  include ::OpenAPIParser::Parser::Value
  include ::OpenAPIParser::Parser::Object
  include ::OpenAPIParser::Parser::List
  include ::OpenAPIParser::Parser::Hash
  include ::OpenAPIParser::Parser::HashBody

  # @return [Core] a new instance of Core
  def initialize(target_klass); end

  private

  # Returns the value of attribute target_klass.
  def target_klass; end
end

module OpenAPIParser::Parser::Hash
  def _openapi_attr_hash_objects; end
  def openapi_attr_hash_object(name, klass, options = T.unsafe(nil)); end
end

module OpenAPIParser::Parser::HashBody
  def _openapi_attr_hash_body_objects; end
  def openapi_attr_hash_body_objects(name, klass, options = T.unsafe(nil)); end
end

module OpenAPIParser::Parser::List
  def _openapi_attr_list_objects; end
  def openapi_attr_list_object(name, klass, options = T.unsafe(nil)); end
end

module OpenAPIParser::Parser::Object
  def _openapi_attr_objects; end
  def openapi_attr_object(name, klass, options = T.unsafe(nil)); end
  def openapi_attr_objects(*names, klass); end
end

module OpenAPIParser::Parser::Value
  def _openapi_attr_values; end
  def openapi_attr_value(name, options = T.unsafe(nil)); end
  def openapi_attr_values(*names); end
end

class OpenAPIParser::PathItemFinder
  # @param paths [OpenAPIParser::Schemas::Paths]
  # @return [PathItemFinder] a new instance of PathItemFinder
  def initialize(paths); end

  # find operation object and if not exist return nil
  #
  # @param http_method [String, Symbol] like (get, post .... allow symbol)
  # @param request_path [String]
  # @return [Result, nil]
  def operation_object(http_method, request_path); end

  def parse_path_parameters(schema_path, request_path); end

  private

  # used to filter paths with different depth or without given http method
  #
  # @return [Boolean]
  def different_depth_or_method?(splitted_schema_path, splitted_request_path, path_item, http_method); end

  # extract params by comparing the request path and the path from schema
  # EXAMPLE:
  # extract_params(['org', '1', 'user', '2', 'edit'], ['org', '{org_id}', 'user', '{user_id}'])
  # => { 'org_id' => 1, 'user_id' => 2 }
  # return nil if the schema does not match
  def extract_params(splitted_request_path, splitted_schema_path); end

  # find matching path and extract params
  # EXAMPLE: find_path_and_params('get', '/user/1') => ['/user/{id}', { 'id' => 1 }]
  def find_path_and_params(http_method, request_path); end

  # check if there is a identical path in the schema (without any param)
  #
  # @return [Boolean]
  def matches_directly?(request_path, http_method); end

  # find all matching paths with parameters extracted
  # EXAMPLE:
  # [
  #    ['/user/{id}/edit', { 'id' => 1 }],
  #    ['/user/{id}/{action}', { 'id' => 1, 'action' => 'edit' }],
  #  ]
  def matching_paths_with_params(request_path, http_method); end

  # get the parameter name from the schema path item
  # EXAMPLE: param_name('{id}') => 'id'
  def param_name(schema_path_item); end

  def parse_request_path(http_method, request_path); end
  def path_parameters(schema_path); end

  # check if the path item is a template
  # EXAMPLE: path_template?('{id}') => true
  #
  # @return [Boolean]
  def path_template?(schema_path_item); end
end

class OpenAPIParser::PathItemFinder::Result
  # @return [Result] a new instance of Result
  def initialize(path_item_object, operation_object, original_path, path_params); end

  # @return [OpenAPIParser::Schemas::Operation]
  def operation_object; end

  # @return [String]
  def original_path; end

  # @return [OpenAPIParser::Schemas::PathItem]
  def path_item_object; end

  # @return [Hash{String => String}]
  def path_params; end
end

class OpenAPIParser::ReferenceExpander
  class << self
    # @param openapi [OpenAPIParser::Schemas::OpenAPI]
    def expand(openapi); end
  end
end

# binding request data and operation object
class OpenAPIParser::RequestOperation
  # @param http_method [String]
  # @param result [OpenAPIParser::PathItemFinder::Result]
  # @param config [OpenAPIParser::Config]
  # @return [RequestOperation] a new instance of RequestOperation
  def initialize(http_method, result, config); end

  # @return [OpenAPIParser::Config]
  def config; end

  # @return [String]
  def http_method; end

  # @return [OpenAPIParser::Schemas::Operation]
  def operation_object; end

  # @return [String]
  def original_path; end

  # Returns the value of attribute path_item.
  def path_item; end

  # @return [Hash{String => String}]
  def path_params; end

  def validate_path_params(options = T.unsafe(nil)); end

  # @param content_type [String]
  # @param params [Hash]
  # @param options [OpenAPIParser::SchemaValidator::Options]
  def validate_request_body(content_type, params, options = T.unsafe(nil)); end

  # @param params [Hash] parameter hash
  # @param headers [Hash] headers hash
  # @param options [OpenAPIParser::SchemaValidator::Options] request validator options
  def validate_request_parameter(params, headers, options = T.unsafe(nil)); end

  # @param response_body [OpenAPIParser::RequestOperation::ValidatableResponseBody]
  # @param response_validate_options [OpenAPIParser::SchemaValidator::ResponseValidateOptions]
  def validate_response_body(response_body, response_validate_options = T.unsafe(nil)); end

  class << self
    # @param config [OpenAPIParser::Config]
    # @param path_item_finder [OpenAPIParser::PathItemFinder]
    # @return [OpenAPIParser::RequestOperation, nil]
    def create(http_method, request_path, path_item_finder, config); end
  end
end

class OpenAPIParser::RequestOperation::ValidatableResponseBody
  # @return [ValidatableResponseBody] a new instance of ValidatableResponseBody
  def initialize(status_code, response_data, headers); end

  def content_type; end

  # Returns the value of attribute headers.
  def headers; end

  # Returns the value of attribute response_data.
  def response_data; end

  # Returns the value of attribute status_code.
  def status_code; end
end

# load data to target_object by schema definition in core
class OpenAPIParser::SchemaLoader
  # @param target_object [OpenAPIParser::Schemas::Base]
  # @param core [OpenAPIParser::Parser::Core]
  # @return [SchemaLoader] a new instance of SchemaLoader
  def initialize(target_object, core); end

  # Returns the value of attribute children.
  def children; end

  # execute load data
  # return data is equal to :children
  #
  # @return [Array<OpenAPIParser::Schemas::Base>]
  def load_data; end

  private

  def all_loader; end

  # Returns the value of attribute core.
  def core; end

  # @param schema_loader [OpenAPIParser::SchemaLoader::Base]
  def load_data_by_schema_loader(schema_loader); end

  def register_child(object); end

  # Returns the value of attribute target_object.
  def target_object; end
end

# loader base class
class OpenAPIParser::SchemaLoader::Base
  # @param variable_name [String]
  # @param options [Hash]
  # @return [Base] a new instance of Base
  def initialize(variable_name, options); end

  # @param _target_object [OpenAPIParser::Schemas::Base]
  # @param _raw_schema [Hash]
  # @return [Array<OpenAPIParser::Schemas::Base>, nil]
  def load_data(_target_object, _raw_schema); end

  private

  # Returns the value of attribute schema_key.
  def schema_key; end

  # Returns the value of attribute variable_name.
  def variable_name; end

  # create instance variable @variable_name using data
  #
  # @param target [OpenAPIParser::Schemas::Base]
  # @param variable_name [String]
  # @param data [Object]
  def variable_set(target, variable_name, data); end
end

# loader base class for create OpenAPI::Schemas::Base object
class OpenAPIParser::SchemaLoader::Creator < ::OpenAPIParser::SchemaLoader::Base
  # @param variable_name [String]
  # @param options [Hash]
  # @return [Creator] a new instance of Creator
  def initialize(variable_name, options); end

  private

  # Returns the value of attribute allow_data_type.
  def allow_data_type; end

  # Returns the value of attribute allow_reference.
  def allow_reference; end

  def build_object_reference_from_base(base, names); end
  def build_openapi_object_from_option(target_object, ref, schema); end

  # @return [Boolean]
  def check_object_schema?(check_schema); end

  # @return [Boolean] Boolean
  def check_reference_schema?(check_schema); end

  def escape_reference(str); end

  # Returns the value of attribute klass.
  def klass; end
end

# hash body object loader
class OpenAPIParser::SchemaLoader::HashBodyLoader < ::OpenAPIParser::SchemaLoader::Creator
  # @param variable_name [String]
  # @param options [Hash]
  # @return [HashBodyLoader] a new instance of HashBodyLoader
  def initialize(variable_name, options); end

  # @param target_object [OpenAPIParser::Schemas::Base]
  # @param raw_schema [Hash]
  # @return [Array<OpenAPIParser::Schemas::Base>, nil]
  def load_data(target_object, raw_schema); end

  private

  # for responses and paths object
  def create_hash_body_objects(target_object, raw_schema); end

  # Returns the value of attribute reject_keys.
  def reject_keys; end
end

# hash object loader
class OpenAPIParser::SchemaLoader::HashObjectsLoader < ::OpenAPIParser::SchemaLoader::Creator
  # @param target_object [OpenAPIParser::Schemas::Base]
  # @param raw_schema [Hash]
  # @return [Array<OpenAPIParser::Schemas::Base>, nil]
  def load_data(target_object, raw_schema); end

  private

  def create_attr_hash_object(target_object, hash_schema); end
  def ref_name_base; end
end

# list object loader
class OpenAPIParser::SchemaLoader::ListLoader < ::OpenAPIParser::SchemaLoader::Creator
  # @param target_object [OpenAPIParser::Schemas::Base]
  # @param raw_schema [Hash]
  # @return [Array<OpenAPIParser::Schemas::Base>, nil]
  def load_data(target_object, raw_schema); end

  private

  def create_attr_list_object(target_object, array_schema); end
  def ref_name_base; end
end

# Specific Object loader (defined by klass option)
class OpenAPIParser::SchemaLoader::ObjectsLoader < ::OpenAPIParser::SchemaLoader::Creator
  # @param target_object [OpenAPIParser::Schemas::Base]
  # @param raw_schema [Hash]
  # @return [Array<OpenAPIParser::Schemas::Base>, nil]
  def load_data(target_object, raw_schema); end

  private

  # @return [OpenAPIParser::Schemas::Base]
  def create_attr_object(target_object, schema); end
end

# data type values loader
class OpenAPIParser::SchemaLoader::ValuesLoader < ::OpenAPIParser::SchemaLoader::Base
  # @param target_object [OpenAPIParser::Schemas::Base]
  # @param raw_schema [Hash]
  # @return [Array<OpenAPIParser::Schemas::Base>, nil]
  def load_data(target_object, raw_schema); end
end

# validate AllOf schema
class OpenAPIParser::SchemaValidator
  include ::OpenAPIParser::SchemaValidator::Validatable

  # @param value [Hash]
  # @param schema [OpenAPIParser::Schemas::Schema]
  # @param options [OpenAPIParser::SchemaValidator::Options]
  # @return [SchemaValidator] a new instance of SchemaValidator
  def initialize(value, schema, options); end

  # execute validate data
  #
  # @return [Object] coerced or original params
  def validate_data; end

  # validate integer value by schema
  # this method use from float_validator because number allow float and integer
  #
  # @param value [Object]
  # @param schema [OpenAPIParser::Schemas::Schema]
  def validate_integer(value, schema); end

  # validate value eby schema
  #
  # @param value [Object]
  # @param schema [OpenAPIParser::Schemas::Schema]
  def validate_schema(value, schema, **keyword_args); end

  private

  def all_of_validator; end
  def any_of_validator; end
  def array_validator; end
  def boolean_validator; end
  def float_validator; end
  def integer_validator; end
  def nil_validator; end
  def object_validator; end
  def one_of_validator; end
  def string_validator; end
  def unspecified_type_validator; end

  # @return [OpenAPIParser::SchemaValidator::Base, nil]
  def validator(value, schema); end

  class << self
    # validate schema data
    #
    # @param value [Hash]
    # @param [OpenAPIParser::Schemas:v:Schema]
    # @param options [OpenAPIParser::SchemaValidator::Options]
    # @return [Object] coerced or original params
    def validate(value, schema, options); end
  end
end

class OpenAPIParser::SchemaValidator::AllOfValidator < ::OpenAPIParser::SchemaValidator::Base
  # coerce and validate value
  #
  # @param value [Object]
  # @param schema [OpenAPIParser::Schemas::Schema]
  def coerce_and_validate(value, schema, **keyword_args); end
end

class OpenAPIParser::SchemaValidator::AnyOfValidator < ::OpenAPIParser::SchemaValidator::Base
  # @param value [Object]
  # @param schema [OpenAPIParser::Schemas::Schema]
  def coerce_and_validate(value, schema, **_keyword_args); end
end

class OpenAPIParser::SchemaValidator::ArrayValidator < ::OpenAPIParser::SchemaValidator::Base
  # @param value [Array]
  # @param schema [OpenAPIParser::Schemas::Schema]
  def coerce_and_validate(value, schema, **_keyword_args); end

  def validate_max_min_items(value, schema); end
end

class OpenAPIParser::SchemaValidator::Base
  # @param validatable [OpenAPIParser::SchemaValidator::Validatable]
  # @return [Base] a new instance of Base
  def initialize(validatable, coerce_value); end

  # need override
  #
  # @param _value [Array]
  # @param _schema [OpenAPIParser::Schemas::Schema]
  def coerce_and_validate(_value, _schema, **_keyword_args); end

  # @return [OpenAPIParser::SchemaValidator::Validatable]
  def validatable; end

  def validate_discriminator_schema(discriminator, value, parent_discriminator_schemas: T.unsafe(nil)); end
end

class OpenAPIParser::SchemaValidator::BooleanValidator < ::OpenAPIParser::SchemaValidator::Base
  include ::OpenAPIParser::SchemaValidator::Enumable

  def coerce_and_validate(value, schema, **_keyword_args); end

  private

  def coerce(value); end
end

OpenAPIParser::SchemaValidator::BooleanValidator::FALSE_VALUES = T.let(T.unsafe(nil), Array)
OpenAPIParser::SchemaValidator::BooleanValidator::TRUE_VALUES = T.let(T.unsafe(nil), Array)

module OpenAPIParser::SchemaValidator::Enumable
  # check enum value by schema
  #
  # @param value [Object]
  # @param schema [OpenAPIParser::Schemas::Schema]
  def check_enum_include(value, schema); end
end

class OpenAPIParser::SchemaValidator::FloatValidator < ::OpenAPIParser::SchemaValidator::Base
  include ::OpenAPIParser::SchemaValidator::Enumable
  include ::OpenAPIParser::SchemaValidator::MinimumMaximum

  # validate float value by schema
  #
  # @param value [Object]
  # @param schema [OpenAPIParser::Schemas::Schema]
  def coerce_and_validate(value, schema, **_keyword_args); end

  private

  def coerce(value); end
  def coercer_and_validate_numeric(value, schema); end
end

class OpenAPIParser::SchemaValidator::IntegerValidator < ::OpenAPIParser::SchemaValidator::Base
  include ::OpenAPIParser::SchemaValidator::Enumable
  include ::OpenAPIParser::SchemaValidator::MinimumMaximum

  # validate integer value by schema
  #
  # @param value [Object]
  # @param schema [OpenAPIParser::Schemas::Schema]
  def coerce_and_validate(value, schema, **_keyword_args); end

  private

  def coerce(value); end
end

module OpenAPIParser::SchemaValidator::MinimumMaximum
  # check minimum and maximum value by schema
  #
  # @param value [Object]
  # @param schema [OpenAPIParser::Schemas::Schema]
  def check_minimum_maximum(value, schema); end

  private

  def validate(value, schema); end
end

class OpenAPIParser::SchemaValidator::NilValidator < ::OpenAPIParser::SchemaValidator::Base
  # @param value [Object]
  # @param schema [OpenAPIParser::Schemas::Schema]
  def coerce_and_validate(value, schema, **_keyword_args); end
end

class OpenAPIParser::SchemaValidator::ObjectValidator < ::OpenAPIParser::SchemaValidator::Base
  # @param value [Hash]
  # @param schema [OpenAPIParser::Schemas::Schema]
  # @param parent_all_of [Boolean] true if component is nested under allOf
  # @param discriminator_property_name [String, nil] discriminator.property_name to ignore checking additional_properties
  def coerce_and_validate(value, schema, parent_all_of: T.unsafe(nil), parent_discriminator_schemas: T.unsafe(nil), discriminator_property_name: T.unsafe(nil)); end
end

class OpenAPIParser::SchemaValidator::OneOfValidator < ::OpenAPIParser::SchemaValidator::Base
  # @param value [Object]
  # @param schema [OpenAPIParser::Schemas::Schema]
  def coerce_and_validate(value, schema, **_keyword_args); end
end

class OpenAPIParser::SchemaValidator::Options
  # @return [Options] a new instance of Options
  def initialize(coerce_value: T.unsafe(nil), datetime_coerce_class: T.unsafe(nil), validate_header: T.unsafe(nil)); end

  # @return [Boolean] coerce value option on/off
  def coerce_value; end

  # @return [Object, nil] coerce datetime string by this Object class
  def datetime_coerce_class; end

  # Returns the value of attribute validate_header.
  def validate_header; end
end

# response body validation option
class OpenAPIParser::SchemaValidator::ResponseValidateOptions
  # @return [ResponseValidateOptions] a new instance of ResponseValidateOptions
  def initialize(strict: T.unsafe(nil), validate_header: T.unsafe(nil)); end

  # @return [Boolean] validate by strict (when not exist definition, raise error)
  def strict; end

  # Returns the value of attribute validate_header.
  def validate_header; end
end

class OpenAPIParser::SchemaValidator::StringValidator < ::OpenAPIParser::SchemaValidator::Base
  include ::OpenAPIParser::SchemaValidator::Enumable

  # @return [StringValidator] a new instance of StringValidator
  def initialize(validator, coerce_value, datetime_coerce_class); end

  def coerce_and_validate(value, schema, **_keyword_args); end

  private

  # @param schema [OpenAPIParser::Schemas::Schema]
  def coerce_date_time(value, schema); end

  def parse_date_time(value, schema); end

  # @param schema [OpenAPIParser::Schemas::Schema]
  def pattern_validate(value, schema); end

  def validate_date_format(value, schema); end
  def validate_email_format(value, schema); end
  def validate_max_min_length(value, schema); end
  def validate_uuid_format(value, schema); end
end

class OpenAPIParser::SchemaValidator::UnspecifiedTypeValidator < ::OpenAPIParser::SchemaValidator::Base
  # @param value [Object]
  def coerce_and_validate(value, _schema, **_keyword_args); end
end

# validate value by schema
# this module for SchemaValidators::Base
#
# @param value [Object]
# @param schema [OpenAPIParser::Schemas::Schema]
module OpenAPIParser::SchemaValidator::Validatable
  # validate integer value by schema
  # this method use from float_validator because number allow float and integer
  #
  # @param _value [Object]
  # @param _schema [OpenAPIParser::Schemas::Schema]
  def validate_integer(_value, _schema); end

  def validate_schema(value, schema, **keyword_args); end
end

# TODO: support 'not' because I need check reference...
# TODO: support 'xml', 'externalDocs'
# TODO: support extended property
module OpenAPIParser::Schemas; end

class OpenAPIParser::Schemas::Base
  include ::OpenAPIParser::Parser
  include ::OpenAPIParser::Findable
  include ::OpenAPIParser::Expandable
  extend ::OpenAPIParser::Parser::ClassMethods

  # @param [OpenAPIParser::Schemas::Base]
  # @return [Base] a new instance of Base
  def initialize(object_reference, parent, root, raw_schema); end

  # override
  def after_init; end

  def inspect; end

  # Returns the value of attribute object_reference.
  def object_reference; end

  # Returns the value of attribute parent.
  def parent; end

  # Returns the value of attribute raw_schema.
  def raw_schema; end

  # Returns the value of attribute root.
  def root; end
end

class OpenAPIParser::Schemas::Components < ::OpenAPIParser::Schemas::Base
  # @return [Hash{String => Header}, nil] header objects
  def headers; end

  # @return [Hash{String => Parameter}, nil]
  def parameters; end

  # @return [Hash{String => RequestBody}, nil]
  def request_bodies; end

  # @return [Hash{String => Response}, nil]
  def responses; end

  def schemas; end
end

class OpenAPIParser::Schemas::Discriminator < ::OpenAPIParser::Schemas::Base
  # @return [Hash{String => String]] Hash{String => String]
  def mapping; end

  # @return [String, nil]
  def property_name; end
end

class OpenAPIParser::Schemas::Header < ::OpenAPIParser::Schemas::Base
  def allow_empty_value; end
  def allow_reserved; end
  def deprecated; end
  def description; end
  def example; end
  def explode; end
  def required; end

  # @return [Schema, Reference, nil]
  def schema; end

  def style; end

  # validate by schema
  #
  # @param value [Object]
  def validate(value); end
end

class OpenAPIParser::Schemas::MediaType < ::OpenAPIParser::Schemas::Base
  # @return [Schema, nil] OpenAPI3 Schema object
  def schema; end

  # validate params by schema definitions
  #
  # @param params [Hash]
  # @param options [OpenAPIParser::SchemaValidator::Options]
  def validate_parameter(params, options); end
end

class OpenAPIParser::Schemas::OpenAPI < ::OpenAPIParser::Schemas::Base
  # @return [OpenAPI] a new instance of OpenAPI
  def initialize(raw_schema, config, uri: T.unsafe(nil), schema_registry: T.unsafe(nil)); end

  # @return [Components, nil]
  def components; end

  # load another schema with shared config and schema_registry
  #
  # @return [OpenAPIParser::Schemas::OpenAPI]
  def load_another_schema(uri); end

  # @return [String, nil]
  def openapi; end

  # @return [Paths, nil]
  def paths; end

  # @return [OpenAPIParser::RequestOperation, nil]
  def request_operation(http_method, request_path); end

  private

  def resolve_uri(uri); end
end

class OpenAPIParser::Schemas::Operation < ::OpenAPIParser::Schemas::Base
  include ::OpenAPIParser::ParameterValidatable

  def deprecated; end
  def description; end
  def operation_id; end
  def parameters; end

  # @return [OpenAPIParser::Schemas::RequestBody, nil] return OpenAPI3 object
  def request_body; end

  # @return [OpenAPIParser::Schemas::Responses, nil] return OpenAPI3 object
  def responses; end

  def summary; end
  def tags; end
  def validate_request_body(content_type, params, options); end

  # @param response_body [OpenAPIParser::RequestOperation::ValidatableResponseBody]
  # @param response_validate_options [OpenAPIParser::SchemaValidator::ResponseValidateOptions]
  def validate_response(response_body, response_validate_options); end
end

class OpenAPIParser::Schemas::Parameter < ::OpenAPIParser::Schemas::Base
  def allow_empty_value; end
  def allow_reserved; end
  def deprecated; end
  def description; end
  def example; end
  def explode; end
  def in; end
  def name; end
  def required; end

  # @return [Schema, Reference, nil]
  def schema; end

  def style; end

  # @param options [OpenAPIParser::SchemaValidator::Options]
  # @return [Object] coerced or original params
  def validate_params(params, options); end
end

class OpenAPIParser::Schemas::PathItem < ::OpenAPIParser::Schemas::Base
  def delete; end
  def description; end
  def get; end
  def head; end

  # @return [Operation]
  def operation(method); end

  def options; end
  def parameters; end
  def patch; end
  def post; end
  def put; end
  def set_path_item_to_operation; end
  def summary; end
  def trace; end
end

class OpenAPIParser::Schemas::Paths < ::OpenAPIParser::Schemas::Base
  # @return [Hash{String => PathItem, Reference}, nil]
  def path; end
end

class OpenAPIParser::Schemas::Reference < ::OpenAPIParser::Schemas::Base
  # @return [Base]
  def ref; end
end

class OpenAPIParser::Schemas::RequestBody < ::OpenAPIParser::Schemas::Base
  include ::OpenAPIParser::MediaTypeSelectable

  # @return [Hash{String => MediaType}, nil] content type to MediaType object
  def content; end

  # @return [String] description data
  def description; end

  # @return [Boolean] required bool data
  def required; end

  # select media type by content_type (consider wild card definition)
  #
  # @param content_type [String]
  # @return [OpenAPIParser::Schemas::MediaType, nil]
  def select_media_type(content_type); end

  # @param content_type [String]
  # @param params [Hash]
  # @param options [OpenAPIParser::SchemaValidator::Options]
  def validate_request_body(content_type, params, options); end
end

class OpenAPIParser::Schemas::Response < ::OpenAPIParser::Schemas::Base
  include ::OpenAPIParser::MediaTypeSelectable

  # @return [Hash{String => MediaType}, nil] content_type to MediaType hash
  def content; end

  def description; end

  # @return [Hash{String => Header}, nil] header string to Header
  def headers; end

  # select media type by content_type (consider wild card definition)
  #
  # @param content_type [String]
  # @return [OpenAPIParser::Schemas::MediaType, nil]
  def select_media_type(content_type); end

  # @param response_body [OpenAPIParser::RequestOperation::ValidatableResponseBody]
  # @param response_validate_options [OpenAPIParser::SchemaValidator::ResponseValidateOptions]
  def validate(response_body, response_validate_options); end

  private

  # @param response_headers [Hash]
  def validate_header(response_headers); end
end

class OpenAPIParser::Schemas::Responses < ::OpenAPIParser::Schemas::Base
  # @return [Response, Reference, nil] default response object
  def default; end

  # @return [Hash{String => Response, Reference}, nil] response object indexed by status code. see: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#patterned-fields-1
  def response; end

  # validate params data by definition
  # find response object by status_code and content_type
  # https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#patterned-fields-1
  #
  # @param response_body [OpenAPIParser::RequestOperation::ValidatableResponseBody]
  # @param response_validate_options [OpenAPIParser::SchemaValidator::ResponseValidateOptions]
  # @raise [::OpenAPIParser::NotExistStatusCodeDefinition]
  def validate(response_body, response_validate_options); end

  private

  # @param status_code [Integer]
  # @return [Response]
  def find_response_object(status_code); end

  # parse 400 -> 4xx
  # OpenAPI3 allow 1xx, 2xx, 3xx... only, don't allow 41x
  #
  # @param status_code [Integer]
  def status_code_to_wild_card(status_code); end
end

class OpenAPIParser::Schemas::Schema < ::OpenAPIParser::Schemas::Base
  # additional_properties have default value
  # we should add default value feature in openapi_attr_object method, but we need temporary fix so override attr_reader
  def additional_properties; end

  # @return [Array<Schema, Reference>, nil]
  def all_of; end

  # @return [Array<Schema, Reference>, nil]
  def any_of; end

  # @return [Object, nil]
  def default; end

  # @return [Boolean, nil]
  def deprecated; end

  # @return [String, nil]
  def description; end

  # @return [Discriminator, nil]
  def discriminator; end

  # @return [Array, nil] any type array
  def enum; end

  # @return [Object, nil]
  def example; end

  # @return [Boolean, nil]
  def exclusiveMaximum; end

  # @return [Boolean, nil]
  def exclusiveMinimum; end

  # @return [String, nil]
  def format; end

  # @return [Schema, nil]
  def items; end

  # @return [Integer, nil]
  def maxItems; end

  # @return [Integer, nil]
  def maxLength; end

  # @return [Integer, nil]
  def maxProperties; end

  # @return [Float, nil]
  def maximum; end

  # @return [Integer, nil]
  def minItems; end

  # @return [Integer, nil]
  def minLength; end

  # @return [Integer, nil]
  def minProperties; end

  def minimum; end

  # @return [Float, nil]
  def multipleOf; end

  # @return [Boolean, nil]
  def nullable; end

  # @return [Array<Schema, Reference>, nil]
  def one_of; end

  # @return [String, nil] regexp
  def pattern; end

  # @return [Hash{String => Schema}, nil]
  def properties; end

  # @return [Boolean, nil]
  def read_only; end

  # @return [Array<String>, nil] at least one item included
  def required; end

  # @return [String, nil]
  def title; end

  # @return [String, nil] multiple types doesn't supported in OpenAPI3
  def type; end

  # @return [Boolean, nil]
  def uniqueItems; end

  # @return [Boolean, nil]
  def write_only; end
end

OpenAPIParser::VERSION = T.let(T.unsafe(nil), String)

class OpenAPIParser::ValidateError < ::OpenAPIParser::OpenAPIError
  # @return [ValidateError] a new instance of ValidateError
  def initialize(data, type, reference); end

  def message; end

  class << self
    # create ValidateError for SchemaValidator return data
    #
    # @param value [Object]
    # @param schema [OpenAPIParser::Schemas::Base]
    def build_error_result(value, schema); end
  end
end
